### PR TITLE
Updating ICM notification views

### PR DESCRIPTION
**Pull request by stevenernst131**
image

image

### CODE REVIEW

**Comment by hforeste** [comment]
Can you add a snapshot of the copied report to notepad?

**Comment by stevenernst131** [comment]
Here is the report:

Summary of impact: Starting 22:57 UTC on 20 Feb 2018, your app may have been impacted due to an App Service outage. Microsoft engineers are actively working to resolve this issue. An alert/technical escalation has already been filed and our Microsoft engineers have been notified. You can check the “Diagnose and solve problems” tab for an updated message, once the issue has been mitigated 

 Details: Between 08:02 and 15:21 UTC on 24 Jan 2018, a subset of customers using App Service in East US may have experienced intermittent latency, timeouts or HTTP 500-level response codes while performing service management operations such as site create, delete and move resources on App Service deployments. Auto-scaling and loading site metrics may also have been impacted.

There is a leading space before details, and its annoying trying to get rid of it but am going with this for now.

**Comment by stevenernst131** [comment]
Leaving this open for you to review @ShekharGupta1988 but I have deployed the changes to prod.

**Comment by ShekharGupta1988** [comment]
looks good. Merging to master.

**Pull request merged**
